server:
  secret: WRYldij9ebtDZ5VJSsxNAfCZ
  addr: :8080
  privateKey: ./ecdsa521key.pem
clients:
- id: testclient
  salt: 321
  accessTTL: 5
  refreshTTL: 15
  redirects:
    - https://oauth.pstmn.io/v1/callback
users:
- username: foo
  password: 695e6f39f5ffd36ae60e0ade727c892d725531455a19c6035cb739d099e8f20e63d3fdfd3241888e38de1d8db85532dd65f817b12fe33ac7cdcc358ef6c8ea23
  salt: moo
- username: bar
  password: 695e6f39f5ffd36ae60e0ade727c892d725531455a19c6035cb739d099e8f20e63d3fdfd3241888e38de1d8db85532dd65f817b12fe33ac7cdcc358ef6c8ea23
  salt: moo
classification:
  - user: foo
    client: testclient
    claims:
      - name: roles
        value: ROLE_USER
  - user: bar
    client: testclient
    claims:
      - name: roles
        value: ROLE_ADMIN